### PR TITLE
Implement player ELOs

### LINKED ISSUE #71: New ELOs for players + teams
[LU council has officially voted in favor of the idea](https://forums.bzflag.org/viewtopic.php?f=114&p=173426&sid=ca03167e5e3a991fb86599b5a9481edd#p173426). So, let's get planning!

### Notes

- LeagueOverseer 1.1.x already reports player BZIDs and we've been using them for Matches so that should be all the information we need going forward.
- All players would start with a base ELO of 1200 same as teams upon creation; ~~we won't retroactively calculate ELOs for players~~
- The ELO will be displayed on player profiles on the site but **not** in player mottos, ~~so the API controller shouldn't need any changes~~

### To do

*Moved to #81*

### PR DESCRIPTION
**Pull request by allejo**
Closes #71 

**Current Status**: Needs double checking with unit tests

### Acronyms for future reference in this PR

- Team vs Team (TvT)
- Mixed vs Team (MvT)
- Mixed vs Mixed (MvM)

### To do

- [x] Player model needs to have new ELO value (only store the current value in this model)
- [x] Create new table to keep track of ELO changes for each match
- [x] `Match::enterMatch()` needs to be updated to update/calculate individual player ELOs and save that
- [x] Possibly retroactively calculate player ELOs based on existing match data which already has player participation
- [x] Update team ELOs respectively
    - [x] "both colors are players from the same teams"
    - [x] "both colors are players from different teams"
    - [x] "only **one** color has players from different teams"
- [x] Handle seasonal ELO resets
- [x] Return a ColorTeam if it's a MvM or MvT match
- [x] Display player ELO change in match summary along with team Elo change for LO API
- [x] Display ELO on player profile with a history of how the ELO has changed
    - [x] Display something when a player hasn't played this season
    - [x] Come up with a non-JS alternative
- [x] Display ELO changes on individual match pages for each player
- [x] Update API endpoint for match reports to not fail when a match doesn't occur between two teams
- [x] Update player ELOs when a match is recalculated
- [x] Support recalculating player ELOs when a match is recalculated
- [x] **Unit tests**; like. omg. a _**lot**_ of unit tests for these changes
- [x] Test web forms to make sure you can enter matches that follow this new format
- [x] Migration needs to be updated to only retroactively do officials (it currently does FMs too for better data)

### Optional (based on time restrictions)

- ~~For the moment, ELO changes won't take cap count into consideration (this is subject to change); let's make this a configurable option if we have time~~

### Specification

[Rankings Logistics for New LU Format.docx](https://github.com/allejo/bzion/files/926545/Rankings.Logistics.for.New.LU.Format.docx)

### Additional Specs

- Player ELOs will reset every season. Seasons defined as 3 month quarters: Q1 Winter (Jan-Mar), Q2 Spring (Apr-June), Q3 Summer (Jul-Sep) and Q4 Fall (Oct-Dec).
- Team A vs Team A official matches will **not** count for player ELO changes and will **not** count towards a team total match count and team ELO changes would cancel out so need for concern. This would allow for players to start rigging the system by letting teammates win.

### CODE REVIEW

**Comment by allejo** [comment]
@llrr12 in scenario 3 of this specification, should the result of the match count towards the team's match count? e.g. Should a team's "win" count increase if they win a Team vs Mixed official match?

**Comment by llrr12** [comment]
Yeah, because the team is considered to have played a match. Their win and total match count should increase, as well as each individual's win/match count.

**Comment by allejo** [comment]
Seasonal ELO resets will occur, so we need to tackle on how to handle this

Seasons are defined as 3 month Quarters: Q1 Winter (Jan-Mar), Q2 Spring (Apr-June), Q3 Summer (Jul-Sep) and Q4 Fall (Oct-Dec).

**Comment by allejo** [comment]
I'm merging this so it longer blocks any other development and I believe I've gotten everything. I've written unit tests for the cases that *I* can think of and there are some weird situations where caching gets in the way of unit tests (so I'll have to rethink those).

I'll have a few players try things out before the next release and write unit tests/fixes if needed. But I think this should do it for this feature (I hope).

**Pull request merged**
